/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  ItemConfig,
  ItemSession,
  PieItemElement,
} from './interface';


export namespace Components {

  interface PieAuthor {
    /**
    * The Pie config model.
    */
    'config': ItemConfig;
    /**
    * To customize the standard behaviour provided by interaction configuration views you can  provide settings key-ed by the package name.  e.g.  `{ '@pie-element/inline-choice': { promptLabel: 'Item Stem' } }`  The settings that are configurable for each authoring view are documented in  the `@package-name/docs` folder for each package.
    */
    'configSettings'?: {[packageName:string]:Object};
  }
  interface PieAuthorAttributes extends StencilHTMLAttributes {
    /**
    * The Pie config model.
    */
    'config'?: ItemConfig;
    /**
    * To customize the standard behaviour provided by interaction configuration views you can  provide settings key-ed by the package name.  e.g.  `{ '@pie-element/inline-choice': { promptLabel: 'Item Stem' } }`  The settings that are configurable for each authoring view are documented in  the `@package-name/docs` folder for each package.
    */
    'configSettings'?: {[packageName:string]:Object};
    /**
    * Emmitted when the model for the content has been updated in the ui.
    */
    'onModelUpdated'?: (event: CustomEvent) => void;
  }

  interface PieLoader {
    /**
    * Loads the custom elments defined by the PIEs, if they are not already loaded.
    */
    'loadPies': (pieHash: PieItemElement) => Promise<void>;
    /**
    * If the bundle is not available yet, the maximum number of milliseconds  between two retries for downloading
    */
    'maxTimeout': number;
    /**
    * If the bundle is not available yet, number of milliseconds before starting  the first retry attempt.
    */
    'minTimeout': number;
    /**
    * If the bundle is not available yet, the number of re-try attempts to download.
    */
    'retries': number;
  }
  interface PieLoaderAttributes extends StencilHTMLAttributes {
    /**
    * If the bundle is not available yet, the maximum number of milliseconds  between two retries for downloading
    */
    'maxTimeout'?: number;
    /**
    * If the bundle is not available yet, number of milliseconds before starting  the first retry attempt.
    */
    'minTimeout'?: number;
    /**
    * If the bundle is not available yet, the number of re-try attempts to download.
    */
    'retries'?: number;
  }

  interface PiePlayer {
    /**
    * The Pie config model.
    */
    'config': ItemConfig;
    /**
    * Describes runtime environment for the player.
    */
    'env': Object;
    /**
    * Indicates if player running in the context of a PIE hosting system. Do not modify the default value for this property if you are not implementing a PIE host. If true, the host is responsible for all model updates.
    */
    'hosted'?: boolean;
    /**
    * If provided this url is used for loading the JS bundle for rendering the PIE Elements. If not provided the system will default to using the PIE Cloud service to locate and load JS bundles.
    */
    'jsBundleUrls'?: Object;
    /**
    * The Pie Session
    */
    'session': ItemSession;
  }
  interface PiePlayerAttributes extends StencilHTMLAttributes {
    /**
    * The Pie config model.
    */
    'config'?: ItemConfig;
    /**
    * Describes runtime environment for the player.
    */
    'env'?: Object;
    /**
    * Indicates if player running in the context of a PIE hosting system. Do not modify the default value for this property if you are not implementing a PIE host. If true, the host is responsible for all model updates.
    */
    'hosted'?: boolean;
    /**
    * If provided this url is used for loading the JS bundle for rendering the PIE Elements. If not provided the system will default to using the PIE Cloud service to locate and load JS bundles.
    */
    'jsBundleUrls'?: Object;
    /**
    * Emmitted if there is an error encountered while rendering. `event.detail` will be a string containing a message about the error.
    */
    'onPlayer-error'?: (event: CustomEvent) => void;
    /**
    * TODO - Emmitted when any all interactions in a PIE Assessment Item have reported that a user  has provided a response to the interaction.
    */
    'onResponseCompleted'?: (event: CustomEvent) => void;
    /**
    * Emmitted when any interaction in the set of interactions being rendered has been mutated by user action.
    */
    'onSession-changed'?: (event: CustomEvent) => void;
    /**
    * The Pie Session
    */
    'session'?: ItemSession;
  }

  interface PieSpinner {}
  interface PieSpinnerAttributes extends StencilHTMLAttributes {}

  interface PieStimulusLayout {}
  interface PieStimulusLayoutAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'PieAuthor': Components.PieAuthor;
    'PieLoader': Components.PieLoader;
    'PiePlayer': Components.PiePlayer;
    'PieSpinner': Components.PieSpinner;
    'PieStimulusLayout': Components.PieStimulusLayout;
  }

  interface StencilIntrinsicElements {
    'pie-author': Components.PieAuthorAttributes;
    'pie-loader': Components.PieLoaderAttributes;
    'pie-player': Components.PiePlayerAttributes;
    'pie-spinner': Components.PieSpinnerAttributes;
    'pie-stimulus-layout': Components.PieStimulusLayoutAttributes;
  }


  interface HTMLPieAuthorElement extends Components.PieAuthor, HTMLStencilElement {}
  var HTMLPieAuthorElement: {
    prototype: HTMLPieAuthorElement;
    new (): HTMLPieAuthorElement;
  };

  interface HTMLPieLoaderElement extends Components.PieLoader, HTMLStencilElement {}
  var HTMLPieLoaderElement: {
    prototype: HTMLPieLoaderElement;
    new (): HTMLPieLoaderElement;
  };

  interface HTMLPiePlayerElement extends Components.PiePlayer, HTMLStencilElement {}
  var HTMLPiePlayerElement: {
    prototype: HTMLPiePlayerElement;
    new (): HTMLPiePlayerElement;
  };

  interface HTMLPieSpinnerElement extends Components.PieSpinner, HTMLStencilElement {}
  var HTMLPieSpinnerElement: {
    prototype: HTMLPieSpinnerElement;
    new (): HTMLPieSpinnerElement;
  };

  interface HTMLPieStimulusLayoutElement extends Components.PieStimulusLayout, HTMLStencilElement {}
  var HTMLPieStimulusLayoutElement: {
    prototype: HTMLPieStimulusLayoutElement;
    new (): HTMLPieStimulusLayoutElement;
  };

  interface HTMLElementTagNameMap {
    'pie-author': HTMLPieAuthorElement
    'pie-loader': HTMLPieLoaderElement
    'pie-player': HTMLPiePlayerElement
    'pie-spinner': HTMLPieSpinnerElement
    'pie-stimulus-layout': HTMLPieStimulusLayoutElement
  }

  interface ElementTagNameMap {
    'pie-author': HTMLPieAuthorElement;
    'pie-loader': HTMLPieLoaderElement;
    'pie-player': HTMLPiePlayerElement;
    'pie-spinner': HTMLPieSpinnerElement;
    'pie-stimulus-layout': HTMLPieStimulusLayoutElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
